version: '3'

services:
  automatic1111:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: automatic1111
    environment:
      - CLI_ARGS=--listen --medvram --xformers --enable-insecure-extension-access --api --allow-code --administrator
    restart: unless-stopped
    ports:
      - "7860:7860"
    volumes:
      - ./data/models:/app/data/models
      - ./data/extensions:/app/data/extensions
      - ./data/embeddings:/app/data/embeddings
      - ./data/outputs:/app/data/outputs
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
